_base_: '../_base_/cityscapes.yml'

batch_size: 16
iters: 100000

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 16
    multi_grid: [1, 1, 2]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 4
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
